spring:
  config:
    import: optional:configserver:http://localhost:8081
  application:
    name: tracking-system
  data:
    mongodb:
      #      uri: mongodb+srv://omar:FcybyLAxvwU6nsxT@cluster0.kp2s5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      #      uri: mongodb://localhost:27017
      username: omar
      password: omar
      host: localhost
      port: 27018
      database: user_tracking
      authentication-database: admin

server:
  port: 9003

