services:

  category:
    image: category:1.0
    container_name: categoryContainer
    ports:
      - "10001:8096"
    networks:
      - app-network
  product:
    image: product:1.0
    container_name: productContainer
    ports:
      - "10002:8095"
    depends_on:
      - category
    networks:
      - app-network
networks:
  app-network:




#
#services:
#
#  mongo:
#    image: mongo
#    container_name: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: omar
#      MONGO_INITDB_ROOT_PASSWORD: omar
#    ports:
#      - "27018:27017"
#    volumes:
#      - mongo_data:/data/db
#    restart: unless-stopped
#
#
#  kafka:
#    image: apache/kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#
#  zipkin:
#    container_name: zipkin
#    image: openzipkin/zipkin
#    ports:
#      - "9411:9411"
#
#  discovery:
#    build: ./discovery
#    image: discovery:1.0
#    container_name: discovery
#    ports:
#      - "8082:8082"
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8082/eureka
#
#  config-server:
#    build: ./config-server
#    image: config-server:1.0
#    container_name: config-server
#    ports:
#      - "8888:8888"
#    depends_on:
#      - zipkin
#    restart: unless-stopped
#
#  gateway:
#    build: ./gateway
#    image: gateway:1.0
#    container_name: gateway
#    ports:
#      - "8888:8888"
#    depends_on:
#      - discovery
#      - config-server
#    environment:
#      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8082/eureka/
#      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
#
#
#
#
#
#
#volumes:
#    mongo_data:
#
