#spring:
#  config:
#    import: optional:configserver:http://localhost:8081
#  application:
#    name: gateway
spring:
  application:
    name: gateway
  cloud:
    config:
      uri: http://config-server:8081