spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: password_wd
  mail:
    host: smtp.gmail.com
    port: 587
    username: salhiomar362@gmail.com
    password: coktmejzvjwpkdbz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9002

application:
  password:
    user:
      url: http://localhost:8888/api/v1/users

