spring:
  data:
    mongodb:
      username: omar
      password: omar
      host: localhost
      port: 27018
      database: password_wd
      authentication-database: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: omarsalhi.trash@gmail.com
    password: 
    
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9002

application:
  password:
    user:
      url: http://localhost:8888/api/v1/users

