server:
  port: 9010
spring :
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/orders/**
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/v1/stripe/**