spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ms?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 9000
  servlet:
    context-path: /api/v1/