spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msCategory?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8091
  servlet:
    context-path: /api/v1/