server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PRODUCT
          uri: lb:http://PRODUCT
          predicates:
            - Path=/api/v1/product, /api/v1/product/**

        - id: CATEGORY
          uri: lb:http://CATEGORY
          predicates:
            - Path=/api/v1/category ,/api/v1/category/**

        - id: CART
          uri: lb:http://CART
          predicates:
            - Path=/api/v1/cart/**

        - id: DISCOUNT
          uri: lb:http://DISCOUNT
          predicates:
            - Path=/api/v1/discount/**

        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/auth/**

        - id: user
          uri: lb://USER
          predicates:
            - Path=/api/v1/users/**

        - id: password
          uri: lb://PASSWORD
          predicates:
            - Path=/api/v1/password/**

        - id: tracking-system
          uri: lb://TRACKING-SYSTEM
          predicates:
            - Path=/graphql, /graphiql, /playground

application:
  security:
    jwt:
      secret-key: 3A3819FB8D35506C579DB26CC2B33952550D02BE99FBF626D8F9C4E8E934F1A3