server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PRODUCT
          uri: lb:http://PRODUCT
          predicates:
            - Path=/api/v1/product, /api/v1/product/**

        - id: CATEGORY
          uri: lb:http://CATEGORY
          predicates:
            - Path=/api/v1/category ,/api/v1/category/**