server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PRODUCT
          uri: lb:http://PRODUCT
          predicates:
            - Path=/api/v1/product, /api/v1/product/**

        - id: CATEGORY
          uri: lb:http://CATEGORY
          predicates:
            - Path=/api/v1/category ,/api/v1/category/**
        - id: CART
          uri: lb:http://CART
          predicates:
            - Path=/api/v1/cart/**
        - id: DISCOUNT
          uri: lb:http://DISCOUNT
          predicates:
            - Path=/api/v1/discount/**