server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: complaint-service
          uri: lb:http://complaint
          predicates:
            - Path=/api/v1/complaint/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/