server:
  port: 8888
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: complaint-service
          uri: lb://complaint
          predicates:
            - Path=/api/v1/complaint/**

        - id: complaintResponse-service
          uri: lb://complaintResponse
          predicates:
            - Path=/api/v1/complaintResponse/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.gateway: DEBUG