server:
  port: 9001
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/orders
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
      user:
        name: admin
        password: admin123

stripe:
  public-key: ${public_key}
  secret-key: ${secret_key}